### ISSUE TITLE
Touch detection works only in upper left side of the screen on iPad

### ISSUE THREAD

**Issue by nozomuplus** [1-10/ZIGSIMPlus_iOS_Public#18]
When using on iPad, "Touch" function works only in upper left side.
Commit ID: 429f7adc19354a09e395be06e5d1cc9ef9a41c97

**Comment by fand** [comment]
This might be a problem that `Touch Area` view was not placed correctly in the storyboard.
I think this is fixed in https://github.com/1-10/ZIGSIMPlus_iOS_Public/pull/28 though I haven't tested on iPad (I don't have iPads..)

**Comment by nozomuplus** [comment]
Confirmed this was fixed on 116c966.
Touch values nearly 1.0 indicates that touch detection works on bottom right.

![IMG_0010](https://user-images.githubusercontent.com/19822628/61442145-05396180-a982-11e9-947b-d68fbdc01feb.PNG)
